#+++++++++++++ DJANGO docker-compose +++++++++++++++++++++++
#
# You can use it to local development.
# Please read a documentation for this project before begin.
#
# Author : Makan DIANKA
# Email  : python3.230492@gmail.com
# Website: makandianka.org
# Chanel : https://www.youtube.com/@pydev5329


version: '3'
services:
  db:
    image: mysql:8.0-debian
    container_name: mysql8
    working_dir: /data
    volumes:
      - ./database:/data
    ports:
      - 2021:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin: 
    image: phpmyadmin
    container_name: phpmyadmin2
    working_dir: /phpmyadmin/data
    volumes:
      - ./phpmyadmin:/phpmyadmin/data
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
  app:
    build: .
    container_name: myapp
    volumes:
      - .:/var/www
    working_dir: /var/www/web
    ports:
      - 2023:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    tty: true
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG}