version: '3'
services:
  app:
    build: .
    container_name: myapp
    volumes:
      - ./webapp:/var/www
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.0-debian
    container_name: db
    working_dir: /data
    volumes:
      - ./database:/data
    ports:
      - 2021:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=team
      - MYSQL_USER_PASSWORD=team
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin: 
    image: phpmyadmin
    container_name: phpmyadmin
    working_dir: /phpmyadmin/data
    volumes:
      - ./phpmyadmin:/phpmyadmin/data
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db